id: IA8DD52A8
legacy_id: P004522
ocr_import_info:
  bdrc_scan_id: W25273
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T10:43:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:11:11.959594+00:00'
last_modified: 2022-09-02 14:12:10.444855
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25273
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW25273
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇམ་དབྱངས་བློ་གྲོས།
  author: བྲག་གཡབ་རྟོགས་ལྡན་འཇམ་དབྱངས་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.4946529115601876
  ocr_word_median_confidence_index: 0.4300000071525574
quality: null
bases:
  I3894:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3894
      total_pages: 1200
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3894.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.4946529115601876
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
