id: P004522
initial_creation_type: ocr
source_metadata:
  id: bdr:W25273
  title: གསུང་འབུམ། འཇམ་དབྱངས་བློ་གྲོས
  author: ''
  volumes:
    f58d224fba3c48d4bbec5024d04a0655:
      image_group_id: I3894
      title: ''
      volume_number: 1
      total_pages: 1200
      base_file: v001.txt
