id: P004522
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:29:26.033053
source_metadata:
  id: bdr:W25273
  title: གསུང་འབུམ། འཇམ་དབྱངས་བློ་གྲོས
  author: ''
  volumes:
    f58d224fba3c48d4bbec5024d04a0655:
      image_group_id: I3894
      title: ''
      volume_number: 1
      total_pages: 1200
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
